### ISSUE TITLE
[BUG] [SP-API] [Reports API]  Reports stuck in IN_QUEUE for very long time

### ISSUE THREAD

**Issue by wolendranh** [amzn/selling-partner-api-docs#2935]
## I'm submitting a...

<pre><code>[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## SP-API Name and Version or Report/Feed Type
SP API Reports - GET_VENDOR_SALES, GET_VENDOR_INVENTORY 

## Expected Behavior

Reports are processed during couple of minutes from time they were created

## Current Behavior
Reports are being stuck in IN_QUEUE for very long time. 
Both GET_VENDOR_SALES, GET_VENDOR_INVENTORY  are stuck IN_QUEUE for considerable amount of time. More then 1 hours. 

## Context/Screenshots

There is a strange behavior with reports. I created single report for GET_VENDOR_SALES, GET_VENDOR_INVENTORY. Then I check reports that are in IN_QUEUE state by calling  `getReports`. There are multiple reports stuck IN_QUEUE which I was not creating! 

This all makes processing of reports impossible

**Comment by jamesp26** [comment]
We are getting this issue too, although the API Status page says there are no issues.

Any update appreciate from the Amazon teams as this is causing reporting issues for us.

**Comment by wolendranh** [comment]
@jamesp26 Seems like thats not issue in my code! 

Have you tried to check `IN_QUEUE` reports also?

**Comment by supermikol** [comment]
Likewise same issue, started around 3 days ago. My reports are coming back IN_QUEUE even after 24 hours

**Comment by puppsupr** [comment]
Hi,
Are you still seeing issues ? If yes, can you please open a [support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) including your complete request, response details and provide me the case number here.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by wolendranh** [comment]
@puppsupr hi! 

It seems to be back to normal today. 

But our application and according to comments here also other developers applications were affected by this SP API issue for about 4 last days - 16.02.23 - 20.02.23. 

There was no communication/announcements from Amazon Team and [SP-API-Status](https://sellercentral.amazon.com/sp-api-status) page remained "all green" during those days. 

Was there known issue or some performance problems in SP API that caused this, how can user-developers of SP API know about such issues in future so we can notify our clients about it? 

This clearly should be posted on SP API status dashboard so developers can act accordingly.

**Comment by SamuelJamesDev** [comment]
Also experiencing this issue currently, are there any updates on a resolution?

**Comment by supermikol** [comment]
> Hi, Are you still seeing issues ? If yes, can you please open a [support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) including your complete request, response details and provide me the case number here.
> 
> Thanks and Regards, Supriya P Solutions Architect, Selling Partner API [SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

Issue was resolved as of yesterday. Thanks.

**Comment by Matt-Selvaraj** [comment]
@supermikol @wolendranh 
I've also been having the same issues with vendor report downloads for about the past week. Reports were downloading as expected yesterday just as you both mentioned, but today they are once again stalling out IN_QUEUE. Are you two facing similar issues? Thanks.

**Comment by wolendranh** [comment]
@puppsupr @Matt-Selvaraj  issue returned today. Reports are once again stuck in IN_QUEUE state

Is there any official statement from Amazon team on this? This is very serious issue.

**Comment by sungolivia** [comment]
Hey everyone, there was a delay with the vendor reports but it should have been resolved. Anyone else aside from @wolendranh still seeing this issue?

**Comment by wolendranh** [comment]
@sungolivia why there is no any communication/announcement regarding this issue not in "announcement" channel, not on Health Dashboard (https://sellercentral.amazon.com/sp-api-status)?

**Comment by Matt-Selvaraj** [comment]
@sungolivia I'm still not able to download GET_VENDOR_INVENTORY reports (they are stuck IN_QUEUE). GET_VENDOR_SALES reports are timing out at the IN_PROGRESS status which might be because a lot of people are trying to download GET_VENDOR_SALES reports right now.

**Comment by wolendranh** [comment]
@sungolivia @puppsupr  
Hi, any updates on this issue?

Vendor reports are still being stuck IN_QUEUE state.

**Comment by jamesp26** [comment]
Problem appeared to be solved but is back again. Crazy that there are no notifcations about an issue that is quite clearly there.

**Comment by wolendranh** [comment]
@sungolivia @puppsupr
Hi, are there any updates on this issue?

Vendor reports are still being stuck IN_QUEUE state and it is NOT resolved.

**Comment by wolendranh** [comment]
@sungolivia @puppsupr
Hi, was there any progress resolving this issue?

Our app has to process multiple reports per day and they are all stuck.

**Comment by puppsupr** [comment]
Hi @wolendranh,

Can you please open a [support case](https://vendorcentral.amazon.com/hz/vendor/members/contact) including your complete request, response details and provide me the case number here.

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)

**Comment by Adam2022Lever** [comment]
Hi @puppsupr 
We are facing the same issue of being stuck in the "In_Queue" status for indefinite periods of time. These are the Case IDs that we have opened. Case ID - 8450591612; 8446851372. We are constantly being asked for more and more information even after providing almost everything, but the resolution is not being addresses.

**Comment by puppsupr** [comment]
Hi Team,

The issue reported here is already resolved. 

As to best practices, we are seeing some developers ask for the same reports over and over again. While changes do occur daily in the system, it is a lot of overhead. Please make sure that you make optimal calls. 

Thanks and Regards,
Supriya P
Solutions Architect, Selling Partner API
[SP API Blogs](https://developer-docs.amazon.com/sp-api-blog/docs/getting-started) | [SP API YouTube Channel](https://www.youtube.com/@amazon-sp-api)
