### ISSUE TITLE
The Product Pricing endpoint fails for SKUs containing forward slashes

### ISSUE THREAD

**Issue by ellis** [amzn/selling-partner-api-docs#467]
How can the product pricing endpoint be used to fetch data on SKUs that contain forward slashes?  Let's say the SKU is: EXAMPLE/SLASH. Here's are several examples of URLs I tested for this issue:

1. https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLE%2FSLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New
2. https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLE/SLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New
3. https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLESLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New

I would expect URL 1 to work, where the slash is URL-encoded.  But it returns a 404 error ("The requested URL was not found on this server.").

Obviously, the URL 2 can't work because of the extra slash.  Here's the error:

```json
{
    "message": "Access to requested resource is denied.",
    "code": "Unauthorized",
    "details": ""
}
```

URL 3 also won't work, because its the wrong SKU, but it produces the appropriate error message:

```json
{
	"code": "InvalidInput",
	"message": "SOMESTRANGE is an invalid SKU for marketplace A1PA6795UKMFR9",
	"details": ""
}
```

Can you add support for SKUs with slashes, like in URL 1?

**Comment by jlevers** [comment]
This isn't an issue I've run into, but have you tried escaping the slash with a backslash, and then possibly URL-encoding that? E.g.:

https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLE\/SLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New

or

https://sellingpartnerapi-eu.amazon.com/products/pricing/v0/listings/EXAMPLE%5C%2FSLASH/offers?MarketplaceId=A1PA6795UKMFR9&ItemCondition=New

**Comment by ellis** [comment]
@jlevers Thanks for the clever suggestion.  Was worth a shot, but it didn't work.  I also tried with two backslashes.

**Comment by dfrdmn** [comment]
I can confirm that this seems to be a problem with other endpoints such as `patchListingsItem`. Any SellerSKU that contains a forward slash simply won't work. We have tried escaping in every way possible, but always end up with `Access to requested resource is denied.`.

**Comment by cgaugel** [comment]
@parvathm , this is an important bug. Please have a look into this!

**Comment by parvathm** [comment]
Hi all,

We are able to reproduce the issue on our end with other endpoint and # in path parameters. We are actively working to find the root cause and will provide an update soon.
Can you all please confirm below points
1. Is the issue with only swagger code generated client libraries (CL) ? Are you using Authentication and Authorization library while generating CL
2. Have you tried the request in postman ? is it successful?

Thanks,
Parvathm,
Selling Partner API Developer Support.

**Comment by AleemFeng** [comment]
hi 
I meet the same problem when my application called getItemOffers.
```java
"code": "InvalidInput",
"message": "B07XXXXXX is an invalid ASIN for marketplace ATVPDKIKX0DER",
"details": ""
could u tell me how to resolve it?

**Comment by ellis** [comment]
@AleemFeng I've only seen that error for ASINs when it's correct.  Open the detail page on Amazon (e.g. https://www.amazon.com/dp/B07XXXXXX), and a 404 page is likely to be shown.  Otherwise, I would raise a case.  To find the right link for raising a case, click the button to create a new issue here, and you'll see the link near the top of the text field.

**Comment by cgaugel** [comment]
@parvathm what is the status here?

**Comment by dfrdmn** [comment]
@parvathm We are using this library: https://github.com/saleweaver/python-amazon-sp-api. It uses the popular python requests library to make the actual call.

**Comment by parvathm** [comment]
Hi,

We recently deployed a fix in Java Authentication and Authorization (A&A) library which solved the issue of having # in path parameters and thought the same will address this issue. Have you used our latest A&A Java version? We might need more details to verify SKUs containing forward slashes. If you already have a support case for this issue please share the case id. 

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by dfrdmn** [comment]
@parvathm I've opened case 8878634621.

**Comment by ellis** [comment]
Hi @parvathm Still not working for me.  If it helps, my most recent attempt has requestId 1fff2df8-8666-4928-b633-ea12ff228ea9 and timestamp 20210917T082628Z.

I opened case 7183887702 on July 20 with a few additional details.

Let me know if you need me to run the request again.

**Comment by cgaugel** [comment]
lol

**Comment by cgaugel** [comment]
@parvathm bug is still there

**Comment by parvathm** [comment]
Hi,

Sorry for late reply. Thank you for providing the case ids , We are working on it and I will get back with an update asap.

@cgaugel If you have a support case for this issues can you please share the case id?
 We need details like which client library you are using and if only swagger code generated libraries are returning this error.

Thanks,
Parvathm,
Selling Partner API Developer support.

**Comment by cgaugel** [comment]
No I don't have any case ids. Here are a lot of case id's you can check. This bug is over 6 month old, are you serious?

**Comment by ellis** [comment]
@parvathm 
> We need details like which client library you are using and if only swagger code generated libraries are returning this error.

The library we use in internal, so there isn't much information I can provide about it.  If relevant, it's written in typescript and uses the 'node-fetch' library, and it works reliably for the other SP-API and Advertising API endpoints.

**Comment by ellis** [comment]
Sorry, clicked the wrong button!

**Comment by parvathm** [comment]
Hi,

Thank you for providing the details. Our team is actively working on this and I will update on ETA soon.
Really appreciate your patience. 

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by parvathm** [comment]
Hi,

We have identified a fix for this issue. I will update it here once it is deployed in few days.
Thank you for your patience.

Thanks,
Parvathm
Selling Partner API Developer Support.

**Comment by ellis** [comment]
@parvathm Many thanks, I can verify that it's working on our end too when we URL-encode the slash (i.e. %2F).  Closing the issue.

**Comment by maktia95** [comment]
The same problem exists, again, for Listings-Items-API. Call getListingsItem if passed the sku with "|" (horizontal slash) goes wrong. This is a big problem and I hope it gets fixed as soon as possible.

B2X_2443714|4 this is, for example, a sku registered in the inventory and it is returned to me in calls of the Reports. It should be fixed asap.

**Comment by LoneRegister** [comment]
It looks like the issue is back for items with forward slashes.
In my case the sku is: "HC/LULLABELLZ-BACKCOMBING-BRUSH/PINK", and the call to getListingsItem, with a url of:

/listings/2021-08-01/items/A3H2R3XQUG9L0K/HC/LULLABELLZ-BACKCOMBING-BRUSH/PINK

Fails with an unauthorized error:

public 'message' => string 'Access to requested resource is denied.' (length=39)
public 'code' => string 'Unauthorized' (length=12)
public 'details' => string '' (length=0)
