### ISSUE TITLE
Bad request error: Developer xxxxx does not have access to this application id.

### ISSUE THREAD

**Issue by diegocvazquez** [amzn/selling-partner-api-docs#584]
I am getting the following error when accessing the resource https://sellingpartnerapi-eu.amazon.com/authorization/v1/authorizationCode, I have crated the case 6923135632 

@ShivikaK I saw that you took care of this kind of issues can you help ? thanks in advance

{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Developer ID xxxxxxxx is not associated with the application id.",
      "details": ""
    }
  ]
}

**Comment by ShivikaK** [comment]
Hello @diegocvazquez 

Thank you for raising this issue.

It will help us investigate the error if you can provide us with the application ID as well. You can share the information here on in the support case.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by diegocvazquez** [comment]
> Hello @diegocvazquez
> 
> Thank you for raising this issue.
> 
> It will help us investigate the error if you can provide us with the application ID as well. You can share the information here on in the support case.
> 
> Thanks,
> Shivika Khare
> Selling Partner API Developer Support

Hello @ShivikaK 
I have updated the ticket ID 6923135632 with the application id you required

**Comment by diegocvazquez** [comment]
@ShivikaK 
The status of the application is:

Published
Current edit is pending approval

Basically our application in in production since years and being used for a lot of sellers, We changed following the documentation the API Type from  MWS to MWS and SP API to start the migration of our application, I think that probably the Application description or some text on it was changed from our side, so this means that we need to wait untill this changes are aprooved to use the Authenticaiton API?

Is this somehow affecting the MWS credentials ? because as I mention before this application is currently in production.

Why does a change in the application description (marketing information) makes the Authentication API not woking, this is just delaying our migration, and we are worried about the deadlines, our application is really big.

Best regards, and thanks for your help
Diego


Thanks for your support

**Comment by diegocvazquez** [comment]
@ShivikaK 
I will follow this issue with the ticket 6923135632 thanks for your support

**Comment by amz-tools** [comment]
@diegocvazquez, @ShivikaK,

can you confirm that the issue is related to the application having been edited and is now in draft mode although it is still published?

We do have the exact same issue: Developer ID not found although the hybrid app is successfully published and Oauth working. And our app has been edited, not really on purpose, rather trying to resolve Oauth issues that are now fixed) and these changes are now in draft mode but app is published.

I have an open support ticket since two weeks now but there is no substantial progress as it seems we have to go through all "standard" Q&A before the issue is passed on to somebody who is more into the topic...

Thanks for your help!

**Comment by diegocvazquez** [comment]
Hi,
we have recerived and email today telling us that the change was approved, the current status of the app is 
"Current edit is approved and pending publishing". In the email says also about 10 days to publish the changes. I have tried today and the error is still there when calling

**Comment by amz-tools** [comment]
@diegocvazquez,

thank you for the info. Actually I wasn't correct about the error, we do have the exact same error, it says "not associated" for us as well. Then I guess I will just try to to save some time and will also try to publish the changes if that might be the problem.

**Comment by diegocvazquez** [comment]
@amz-tools 
I was told by support that the issue is related the app status, I have created a ticket, what I did is to create a second app to do all the testing, good luck!

**Comment by diegocvazquez** [comment]
Hello there I am facing the same issue regarding the Authorization API the error is:
Developer ID 9xxxx7is not associated with the application id.

Our application is a Hybrid approved and published Application, I have created the case ID7011006982
Can you please help us?

thanks for your support

**Comment by LukeLim81** [comment]
@ShivikaK 

Hello, I am facing the same issue.
My case id is 8475733711

Can you please help us?

Thanks

**Comment by ShivikaK** [comment]
Hello @LukeLim81 

Thank you for reaching out

Your case 8475733711 is regarding approval for app publish to Appstore which has been responded to recently with further details. Once your app is published, please open a support case with us for this issue if needed.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by copyboy** [comment]
@ShivikaK 
Hello, I am facing the same issue.
My case ID8190927951

Can you please help us?

Thanks

**Comment by S4T-TP** [comment]
@ShivikaK

Hello, we are facing the same issue.
Our case ID is 6916088232.

Can you please help us?

Thanks.

**Comment by philmccarty** [comment]
Hi @ShivikaK @parvathm 

I'm having the exact same issue here, and the person handling my case seems
to be unaware of the configuration issue:
Case ID: 2332552843

Thanks so much,
Phil
