### ISSUE TITLE
[BUG] Documentation 

### ISSUE THREAD

**Issue by PrashantMalaviya** [amzn/selling-partner-api-docs#734]
I try to application Authorization but the Amazon sends me the authorization information is the only this :

https://myappurl?spapi_oauth_code=code&state=stateexample&selling_partner_id=ID

not send to the MWS Token 

Why????

**Comment by nodisk8800** [comment]
Auth youself ,is not return MWS Token.

**Comment by PrashantMalaviya** [comment]
hello @nodisk8800 sir,
this is the documentation call...link :- https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-application

screen short:
![Untitled](https://user-images.githubusercontent.com/68289893/118351397-798ebd00-b579-11eb-994b-b307f9747d20.png)

**Comment by stefnats** [comment]
Have you tried sending the `version=beta` flag? Maybe this fixes it.

**Comment by PrashantMalaviya** [comment]
I try ...but not working..

**Comment by ShivikaK** [comment]
Hello @PrashantMalaviya 

Thank you for raising this issue.

Please note that if you are the selling partner authorizing the hybrid SP-API application and the application owner i.e. if this test if for your own seller account which was also used to create the hybrid application, you will not receive the MWSAuthToken. 

Please confirm if this is a self-authorization use case being used for Website workflow test.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
Hello sir @ShivikaK ,
       This is Website workflow test.

Thanks,
Prashant Malaviya
Developer

**Comment by Tomer781** [comment]
Hello @ShivikaK 
I'm also experiencing the same issue. I Don't know about @PrashantMalaviya situation, but for me, it's **Not** a self authorization.
I have a user which is the application owner, and the application is a brand new hybrid draft application. I'm using an oAuth authorization url, including the version=beta of course, and login to amazon using a different user. I'm not getting the mws_auth_token... I'll mention that the users are from different regions, if that can cause any problems.

**Comment by ShivikaK** [comment]
Hello @Tomer781 

Can you provide us with your application ID information and OAuth URL constructed to test the workflow?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
> Hello sir @ShivikaK ,
> This is Website workflow test.
> 
> Thanks,
> Prashant Malaviya
> Developer

Hello @PrashantMalaviya 

Is this website workflow test for a self-authorization scenario? Or are you testing this with a different seller account that is not the one associated with the hybrid application?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
@ShivikaK hello sir,
This is test works in other account

**Comment by Tomer781** [comment]
@ShivikaK
amzn1.sp.solution.67eb191d-5881-4656-84c0-4efbd88cd9fa
https://sellercentral.amazon.co.uk/apps/authorize/consent?application_id=amzn1.sp.solution.67eb191d-5881-4656-84c0-4efbd88cd9fa&state=test&version=beta
Thank you!

**Comment by ShivikaK** [comment]
Hello @Tomer781 

Thank you for providing the details. I will report this to the concerned team for further investigation.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
> @ShivikaK hello sir,
> This is test works in different seller account and not the self-authorization.

Hello @PrashantMalaviya 

I will appreciate if you can also provide me with your application ID to report the same issue that you are facing.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
@ShivikaK sir,
This is my application is :- 
application_id=amzn1.sp.solution.dbf5d163-a097-4313-8ca4-36e191d5c586

**Comment by ShivikaK** [comment]
Hello @Tomer781 & @PrashantMalaviya 

Thank you for providing the app ID information. Can you please confirm the merchant ID on behalf of whom this workflow was tested along with an approximate timestamp for the OAuth handshake?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello,

Kindly disregard my above comment.

The issue has been identified and have fixed it. Can you try testing the workflow again and confirm that issue is resolved?

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
hello Sir @ShivikaK ,
i try but it is not to solved,
my connect seller acount link is :-
link :- https://sellercentral-europe.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.dbf5d163-a097-4313-8ca4-36e191d5c586&version=beta&state=test


sir ,@Tomer781 can you solved ????

**Comment by PrashantMalaviya** [comment]
Hello sir @ShivikaK  it's solved the error....done...thank you for your support ...
Forget the upper comments....thank you..👍
Done.

**Comment by xzz953337446** [comment]
@PrashantMalaviya & @ShivikaK   hello sir,i have the same problem  ,can you tell me how to solve it ?  it's Website workflow test ,I use an oAuth authorization url which include the version=beta , and i am sure  it's Not a self authorization ,but no MWS Token.

**Comment by Tomer781** [comment]
Hi @ShivikaK,
I'm sorry about the delay, I have checked if the problem has been resolved, and unfortunately not yet...

**Comment by Rally0618** [comment]
Hello @ShivikaK 

I have same problem.
Application Id: amzn1.sp.solution.9cdbd6dd-eefa-4fa5-ac76-dd69550218a6
https://sellercentral.amazon.com/apps/authorize/consent?application_id=amzn1.sp.solution.9cdbd6dd-eefa-4fa5-ac76-dd69550218a6&state=00b87e22-5081-4fb5-b432-fcccb22c7bec@6447&version=beta

Thanks,
Rally

**Comment by ShivikaK** [comment]
Hello everyone,

Thank you for letting us know about the issue. The bug is again being investigated and I will let you know once I have an update on the resolution for the same.

I apologize for the inconvenience this has caused so far.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
Hello @ShivikaK sir,
My app is under testing and I show this issue but in case in future traffic in my app and that's time one's again this issue generates ??? Than ...

**Comment by PrashantMalaviya** [comment]
hello @ShivikaK sir,
How to add the other country OAuth Login URI or OAuth Authorization URI in this :-
how to add and connect the other country seller  :- 
![Untitled2](https://user-images.githubusercontent.com/68289893/119453265-dbf37480-bd54-11eb-9766-c49807927d05.png)

**Comment by xzz953337446** [comment]
@ShivikaK Well, can I have an bug fix date?

**Comment by ShivikaK** [comment]
> hello @ShivikaK sir,
> How to add the other country OAuth Login URI or OAuth Authorization URI in this :-
> how to add and connect the other country seller :-
> ![Untitled2](https://user-images.githubusercontent.com/68289893/119453265-dbf37480-bd54-11eb-9766-c49807927d05.png)

Hello @PrashantMalaviya 

The login URI can be only one URI, you cannot have multiple login URIs for the application. You can only have multiple redirect URIs. Also please keep in mind that OAuth Login URI is not the OAuth authorization URI. 

The OAuth Login URI defines the login page of your website during authorization. This URI is shown after a seller consents to authorize your application.

The OAuth Redirect URI is used to redirect the browser to your application after authorization. You can specify more than one redirect by including the redirect_uri parameter in the OAuth URL. If the redirect_uri parameter is not specified, it will default to the first OAuth Redirect URI you’ve defined. 

Note: OAuth Redirect URI does not support localhost: URIs. 

Hope this helps answer your questions.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by ShivikaK** [comment]
Hello everyone,

The bug is currently being investigated and I do not have an ETA for the fix yet. But it is being treated with high priority and I will provide an update once the fix is deployed.

Apologies for the delay this is causing.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by PrashantMalaviya** [comment]
Hello @ShivikaK sir,
But how to use or listings my application in other countries seller use ??
Any documents ??

**Comment by Tomer781** [comment]
@ShivikaK Any news?

**Comment by ShivikaK** [comment]
Hello everyone,

The configuration issue that was identified has been fixed.

To resolve this issue, please follow below steps and let me know if issue persists -

1. Edit your SP API application
2. Uncheck a role and save the form
3. Then again click on Edit App
4. Select the unchecked role and save the form again
5. Try to test the OAuth workflow process and verify if MWS Auth token is returned as expected

If you still run into issues please let me know.

Thanks,
Shivika Khare
Selling Partner API Developer Support

**Comment by Tomer781** [comment]
Hi @ShivikaK 
It's still doesn't work for me after following the steps

**Comment by Tomer781** [comment]
Hi @ShivikaK 
I still don't get the mws_auth_token, can you re check what seems to be the problem?
I'm providing my application details again.
amzn1.sp.solution.67eb191d-5881-4656-84c0-4efbd88cd9fa
https://sellercentral.amazon.co.uk/apps/authorize/consent?application_id=amzn1.sp.solution.67eb191d-5881-4656-84c0-4efbd88cd9fa&state=test&version=beta

I'll really appreciate your help
